### ISSUE TITLE
Improv Wi-Fi over Serial fails on "web.esphome.io"

### ISSUE THREAD

**Issue by Grandzebu** [esphome/esp-web-tools#646]
Cross-testing was performed with 2 computers, 2 browsers and two types of ESP8266

Operating System and navigator :
- Windows 10 with Chrome 141 or Firefox 144 (With WebSerial add-on)
- Windows 7 with Chrome 109 or Firefox 115 (With WebSerial add-on)
USB serial adaptator: PL2303HX or CP2102
Device : ESP8266-01 or ESP8266-12F

1 - Connect GPIO0 to ground, then connect USB: OK
2 - Click "CONNECT" and select the serial port: OK
3 - Click "Prepare for first use" then "INSTALL": OK
4 - The installation takes less than a minute and then the message "Configuration installed !" : OK
5 - Disconnect GPIO0 and reset of the ESP : OK
6 - Click "CLOSE". Appearance of a popup with "esphome-web-619a6e Software: esphome.web/25.9.1" then click "Connect to WIFI" : OK
7 - The list of networks appears; select the network and enter the password. Then click "CONNECT" : OK
8 - The popup shows "esphome-web-619a6e - Provisioning" and spins for a moment **before returning to password entry. : NOT OK**

**Can't go any further**
Uploading a bin file with YAML and network settings works without any problems.

**Comment by balloob** [comment]
Should have been fixed.

**Comment by skipfire** [comment]
@balloob it is not fixed. I have devices where it worked on older versions of ESPHome, but Improv no longer works on them.
